#pragma once

// WORLD & WINDOW CONFIGURATION
#define PIXELS_PER_METER 50.f
#define WORLD_HEIGHT 2250.f
#define WORLD_WIDTH 4000.f
#define DEF_HEIGHT 450.f
#define DEF_WIDTH 800.f
#define WALL_THICKNESS 30.f
#define HALF_WALL_THICKNESS (WALL_THICKNESS / 2)
#define WALL_COLOR sf::Color(140, 140, 140, 255)
#define ZOOM_STEP 0.025f
#define PAN_SPEED 15.f

// UI CONFIGURATION
#define Y_ITEM_SPACING 6.0f

// TOOLS CONFIGURATION
#define TOOLS_ICON_SIZE 32
#define TOOL_BG_COLOR sf::Color(41, 74, 122, 102)
#define TOOL_SELECT_COLOR sf::Color(66, 150, 250, 200)

// ENGINE CONFIGURATION
#define DEFAULT_SOLVER RK4

#define DEFAULT_CALC_FREQ 20 // Hz
#define MAX_CALC_FREQ 1000   // Hz
#define MIN_CALC_FREQ 10      // Hz
#define CALC_FREQ_STEP 10     // Hz

#define MAX_DT 0.05f         // seconds

// PHYSICS CONFIGURATION
#define MIN_GRAVITY -50.0f
#define MAX_GRAVITY 50.0f
#define GRAVITY_STEP 0.5f
#define DEFAULT_GRAVITY Vec2(0.0f, 10.0f)

#define MIN_AIR_DENSITY 0.0f
#define MAX_AIR_DENSITY 10.0f
#define AIR_DENSITY_STEP 0.1f
#define DEFAULT_AIR_DENSITY 1.225f

// OBJECT & TOOL PROPERTIES LIMITS & DEFAULTS
#define MIN_LENGTH 0.1f
#define MAX_LENGTH 10.0f
#define LENGTH_STEP 0.05f
#define DEFAULT_LENGTH 0.25f

#define MIN_DENSITY 0.1f
#define MAX_DENSITY 100.0f
#define DENSITY_STEP 0.5f
#define DEFAULT_DENSITY 1.0f

#define MIN_FORCE 0.0f
#define MAX_FORCE 500.0f
#define FORCE_STEP 5.0f
#define DEFAULT_FORCE 50.0f
#define MAX_ATTENUATION 1.0f
#define FORCE_SCALE 0.05f

#define MIN_DRAG 0.0f
#define MAX_DRAG 1.0f
#define DRAG_STEP 0.02f
#define DEFAULT_DRAG 0.0f

#define MIN_FRICTION 0.0f
#define MAX_FRICTION 1.0f
#define FRICTION_STEP 0.02f
#define DEFAULT_FRICTION 0.0f

#define MIN_RESTITUTION 0.0f
#define MAX_RESTITUTION 1.0f
#define RESTITUTION_STEP 0.02f
#define DEFAULT_RESTITUTION 0.7f

#define MIN_SPRING_CONSTANT 0.1f
#define MAX_SPRING_CONSTANT 10.0f
#define SPRING_CONSTANT_STEP 0.1f
#define DEFAULT_SPRING_CONSTANT 1.0f
